---
apiVersion: v1
kind: Service
metadata:
  name: ambassador-pro-ratelimit
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: RateLimitService
      name: ambassador-pro-ratelimit
      service: "ambassador-pro-ratelimit:8081"
spec:
  type: ClusterIP
  selector:
    service: ambassador
  ports:
  - name: ratelimit-grpc
    port: 8081
    targetPort: 8081
  - name: ratelimit-debug
    port: 6070
    targetPort: 6070