apiVersion: getambassador.io/v1beta1
kind: RateLimit
metadata:
  name: pythonnode-rate-limit
spec:
  domain: ambassador
  limits:
   - pattern: [{generic_key: pythonnode}]
     rate: 5
     unit: minute